### ISSUE TITLE
raw_join missing "JOIN" in Statement?

### ISSUE THREAD

**Issue by riconeitzel** [j4mie/idiorm#353] opened 2019-09-06 14:34 UTC
I just stumbled upon this function and I noticed some SQL errors.

```php 
$rawJoin = 'keywords.name = search_console.name AND keywords.domain_id = domain.id';

$count = ORM::for_table('search_console')
                ->join('domain', ['search_console.domain', '=', 'domain.name'])
                ->raw_join('keywords', $rawJoin, NULL)
                ->where_null('search_console.keyword_id')
                ->count();
```

https://github.com/j4mie/idiorm/blob/ee3022fcf71232309112714ca4a7760105002f99/idiorm.php#L1066

In order to get this running I had to add "JOIN " in front of the referenced raw join string.

Is this a bug in idiorm or am I just holding it wrong?! 🤨

Thanks :-)
Rico

**Comment by treffynnon** [comment] 2019-09-06 22:55
When using raw join you must supply the JOIN keyword of your choice. This
is by design as you might want a left, right, inner, etc join so it allows
you to choose.

See the documentation for an example of it in action:
https://idiorm.readthedocs.io/en/latest/querying.html#raw-join-clauses

I would also recommend changing your code to make use of the parameter
binding rather than directly concatenating strings in your join clause.
It's a safer way of supplying those variable values.

**Comment by treffynnon** [comment] 2019-09-10 04:01
I am assuming this resolved your issue so I am closing this ticket. If you're still having problems then feel free to comment and I'll do my best to help further.

**Closed by treffynnon** 2019-09-10 04:01 UTC

**Comment by riconeitzel** [comment] 2019-09-17 10:07
Thanks for the heads up … I misunderstood the usage of the method. the signature implies, the first parameter is a TABLE name … instead it's the KEYWORD (join) AND the table name.

It would make more sense to have an additional parameter with the JOIN keyword.

thanks for your immediate help ;-)
